### ISSUE TITLE
Dragging is non-functional in Leaflet 1.0

### ISSUE THREAD

**Issue by mnorton-ffs** [publiclab/Leaflet.DistortableImage#64]
Just updated to Leaflet 1.0 to fix some issues elsewhere, and I've found that when initiating a DistortableImageOverlay now, I can still manipulate the corners of the image, but I can't drag it around anymore.

**Comment by mnorton-ffs** [comment]
The implementation is pretty generic so I think it may be a compatibility issue:

`this.image = new L.DistortableImageOverlay(objectURL, {}).addTo(this.leaf);
L.DomEvent.on(self.image._image, 'load', self.image.editing.enable, self.image.editing);`

**Comment by jywarren** [comment]
Thanks! Hmm, you think just the drag listener? Sorry, can you elaborate on your last comment? 

Thanks for catching this!

**Comment by mnorton-ffs** [comment]
So when I manipulate the EditHandles, those work just fine, but dragging the entire overlay around by click+dragging the image itself is non-functional.

**Comment by jywarren** [comment]
Was the code you cited from your own usage, or from one of the examples? I'll look into whether the API for image overlays has changed; maybe we can just update our constructor to get it working in Leaflet 1.0. Thanks!

**Comment by mnorton-ffs** [comment]
It's the code I'm currently using in my project, where 'this.leaf' is a Leaflet map.

**Comment by jywarren** [comment]
Hi, I found that I saw the error: 

    leaflet.distortableimage.js:440 Uncaught TypeError: L.DomUtil.getTranslateString is not a function

It corresponds to these two lines in the source:

1. https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/DistortableImageOverlay.js#L135
2. https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/DistortableImageOverlay.js#L162

I left an issue (you can see it above) on the Leaflet issue tracker, as I wasn't able to find a recommended replacement for `L.DomUtil.getTranslateString` in the 1.0.0 API, but it's clearly been deprecated and is missing from the new docs: http://leafletjs.com/reference-1.0.0.html

Hopefully they get back to us; I'd love to be compatible with 1.0.x when it sees a final release. 

Thanks again for reporting!

**Comment by jywarren** [comment]
The trouble with `L.DomUtil.getTranslateString` seems to be solvable, and I have that dealt with in a local branch. Now I'm seeing the issue you saw, where I can move the corners but not the image itself. I suspect it's about a change in the mouse events... our interception of that is probably not working anymore. Looking a bit deeper.

**Comment by mnorton-ffs** [comment]
You submitted a PR with that fix a while ago, I was referring to the additional issue with image drag.

**Comment by jywarren** [comment]
Ah, yes, you're right -- sorry, it's been a while, yikes. #65. 

Can you file a question about upgrading to v1.0 and mouse events on the Leaflet repo? 

And/or search through existing issues for anything like this? https://github.com/Leaflet/Leaflet/search?q=mouse&type=Issues&utf8=%E2%9C%93

**Comment by mnorton-ffs** [comment]
There doesn't seem to be an issue that quite matches this one, I can file a question about it. One question I have however, since the corners are still draggable in 1.0, could it just be an issue specifically with the image being dragged?

**Comment by jywarren** [comment]
Some more research: image drag handling is done here: https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/edit/DistortableImage.Edit.js#L127

Leaflet v0.7.7 Draggable class: http://leafletjs.com/reference.html#draggable
Leaflet v1.0.0 Draggable class: http://leafletjs.com/reference-1.0.0.html#draggable

**Comment by jywarren** [comment]
Both inherit event handling from similar classes:

v0.7.7: Events methods: http://leafletjs.com/reference.html#events
v1.0.0: Evented: http://leafletjs.com/reference-1.0.0.html#evented

**Comment by jywarren** [comment]
I wonder if it's related to "event bubbling" in that the drag is not being passed to the image, but is being "consumed" by the map itself. Could be worth asking if event bubbling has been changed.

**Comment by jywarren** [comment]
it'd be good to check if this line is actually firing: https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/edit/DistortableImage.Edit.js#L58

**Comment by jywarren** [comment]
Thanks!

**Comment by jywarren** [comment]
Code execution never reaches https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/edit/DistortableImage.Edit.js#L58, on testing.

**Comment by adolmajian** [comment]
Anyone managed to solve the dragging issue yet?

**Comment by jywarren** [comment]
Wow, i must've missed this update -- i'm going to try this directly. Hopefully it solves @viswanathamsantosh's problem in #72 as well.

**Comment by jywarren** [comment]
I've merged #65 -- confirmed it worked! Many thanks to everyone on this thread, esp. @adolmajian for the submitted fix. Released `v0.1.0` and pending checks if it works in Leaflet `v1.1.x` -- any help in testing that also appreciated -- in #72.
