### ISSUE TITLE
Error with Browserify

### ISSUE THREAD

**Issue by adriankwiat** [publiclab/Leaflet.DistortableImage#548]
I'm using this plugin with npm and Browserify. After update to 0.12.6 compiling gives me an error:
```
Error: Cannot find module './transport-list' from 'D:\html\test\node_modules\leaflet-distortableimage\dist'
    at D:\html\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (D:\html\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\html\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at D:\html\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

Command used (it works with 0.11.6):
```
npx browserify index.js -o bundle.js
```

package.json:
```json
{
  "dependencies": {
    "leaflet-distortableimage": "^0.12.6"
  },
  "devDependencies": {
    "browserify": "^16.5.0"
  }
}
```

index.js:
```js
require('leaflet-distortableimage');
```

**Comment by sashadev-sky** [comment]
@adriankwiat haven't used browserify before but it seems like it is not resolving the path correctly. Have you tried something like this solution: https://stackoverflow.com/questions/31713679/node-web-project-bower-browserify?

@VladimirMikulic @jywarren any suggestions here?

**Comment by VladimirMikulic** [comment]
This seems to be an issue with your bundler `browserify`.
It works just fine with others.
I am closing this since it's not our error, `browserify` is old tech.

**Comment by adriankwiat** [comment]
@sashadev-sky thanks, it worked. But I had to add over 70 paths to `external`.

**Comment by sashadev-sky** [comment]
@VladimirMikulic yeah its not an error, its nice to help users find a way to make it compatible with whatever tools they are using though! 

@adriankwiat do you think it's worth sharing so I can document what you had to do to make it compatible? Or is the problem specific to your browserify setup?

**Comment by sashadev-sky** [comment]
i mention this also because I'm a little lost if its necessary to add [this recommendation](https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#module-loaders) from the Leaflet Plugin guide to support Browserify @adriankwiat @VladimirMikulic. 

What exactly would that change for a Browserify user?

**Comment by VladimirMikulic** [comment]
@sashadev-sky I agree that it's nice to help them, but switching bundler would be the best help they could get :)

I am not sure if I understand your question about the plugin recommendation.
It's there for a reason, right?

**Comment by sashadev-sky** [comment]
Yeah we don't currently do that, wondering how adding a file with that code would change the experience for a browserify user? Doesn't seem like it has anything to do with the issue faced here right?

**Comment by VladimirMikulic** [comment]
These two are not connected, true. I don't see the purpose of adding this to our codebase, shouldn't a developer of UMD based project add this when he wants to create a plugin?

**Comment by adriankwiat** [comment]
Here is my code:
https://gist.github.com/adriankwiat/180bfdba1ffc0128514cd8dc625d753c

But when I did it, I got #559 too.

**Comment by VladimirMikulic** [comment]
@adriankwiat link to your repo?
